export const CHANGE_CURRENT_THEME_ID = 'CHANGE_CURRENT_THEME_ID';
export const CHANGE_GO_TYPES = 'CHANGE_GO_TYPES';
export const CHANGE_MODEL = 'CHANGE_MODEL';
export const JUDGE_COLLECT_STATE = 'JUDGE_COLLECT_STATE';